import { Check, Clipboard, ExternalLink, ShieldCheck } from 'lucide-react'
import { FormEvent, useEffect, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { confirmVerification, getVerificationChallenge, saveSetupSessionToken, saveVerificationChallenge, startVerification } from '../api'
import type { Challenge } from '../types'

export default function VerificationPage(){
  const [username,setUsername]=useState('');const [challenge,setChallenge]=useState<Challenge|null>(()=>getVerificationChallenge());const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [copied,setCopied]=useState(false);const navigate=useNavigate();const [searchParams]=useSearchParams()
  const finishVerification=async(challengeId:string)=>{setBusy(true);setError('');try{const result=await confirmVerification(challengeId);saveSetupSessionToken(result.sessionToken);navigate('/profile/edit?verified=1',{replace:true})}catch(err){setError(err instanceof Error?err.message:'Token not found yet')}finally{setBusy(false)}}
  useEffect(()=>{const resumeId=searchParams.get('resume');if(resumeId)finishVerification(resumeId)},[])
  const start=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const next=await startVerification(username);saveVerificationChallenge(next);setChallenge(next)}catch(err){setError(err instanceof Error?err.message:'Could not start verification')}finally{setBusy(false)}}
  const confirm=async()=>{if(challenge)await finishVerification(challenge.challengeId)}
  const copy=()=>{if(!challenge)return;navigator.clipboard.writeText(challenge.token);setCopied(true);setTimeout(()=>setCopied(false),1800)}
  return <main className="narrow-page"><div className="page-heading"><p className="eyebrow">Account verification</p><h1>Prove it’s your LeetCode profile.</h1><p>We only check your public About section. Your password, cookies, and session tokens stay private.</p></div><div className="stepper"><span className="active">1. Username</span><i/><span className={challenge?'active':''}>2. Add code</span><i/><span>3. Set up profile</span></div>
    {!challenge?<form className="surface form-card" onSubmit={start}><div className="form-icon"><ShieldCheck/></div><h2>Enter your LeetCode username</h2><p>We’ll fetch your public stats and create a one-time verification code.</p><label>LeetCode username<input name="username" autoComplete="username" autoFocus required minLength={1} maxLength={30} value={username} onChange={e=>setUsername(e.target.value)} placeholder="your_username"/></label>{error&&<p className="form-error">{error}</p>}<button className="primary wide" disabled={busy}>{busy?'Checking…':'Continue'}</button></form>
    :<div className="surface form-card"><div className="form-icon"><Clipboard/></div><h2>Add this code to your About section</h2><ol className="instructions"><li>Open your LeetCode profile settings.</li><li>Paste the code anywhere in your public <strong>About Me</strong>.</li><li>Save, then come back and check it.</li></ol><button className="token-box" onClick={copy}><code>{challenge.token}</code><span>{copied?<><Check size={16}/> Copied</>:<><Clipboard size={16}/> Copy</>}</span></button><a className="secondary-link" href="https://leetcode.com/profile/" target="_blank" rel="noreferrer">Open LeetCode profile settings <ExternalLink size={15}/></a>{error&&<p className="form-error">{error}</p>}<button className="primary wide" onClick={confirm} disabled={busy}>{busy?'Checking public profile…':'I added it — check now'}</button><button className="text-button" onClick={()=>setChallenge(null)}>Use a different username</button><p className="fine-print">Code expires {new Date(challenge.expiresAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}.</p></div>}
  </main>
}
